"""DealerThread and Campaign state machines (plan 3.1, 3.2). All transitions are code."""

from __future__ import annotations

from enum import StrEnum


class TS(StrEnum):
    DISCOVERED = "DISCOVERED"
    CONTACT_RESOLVED = "CONTACT_RESOLVED"
    UNREACHABLE = "UNREACHABLE"
    OUTREACH_SENT = "OUTREACH_SENT"
    FOLLOW_UP_1 = "FOLLOW_UP_1"
    PHONE_NUDGE = "PHONE_NUDGE"
    NO_RESPONSE = "NO_RESPONSE"
    OPTED_OUT = "OPTED_OUT"
    ENGAGED = "ENGAGED"
    PUSH_FOR_WRITTEN_OTD = "PUSH_FOR_WRITTEN_OTD"
    IN_PERSON_ONLY = "IN_PERSON_ONLY"
    SUBSTITUTE_PROPOSED = "SUBSTITUTE_PROPOSED"
    QUOTE_RECEIVED = "QUOTE_RECEIVED"
    VALIDATING = "VALIDATING"
    REQUEST_ITEMIZATION = "REQUEST_ITEMIZATION"
    QUOTED = "QUOTED"
    NEGOTIATING = "NEGOTIATING"
    FINAL_OFFER = "FINAL_OFFER"
    SHORTLISTED = "SHORTLISTED"
    ELIMINATED = "ELIMINATED"
    SELECTED = "SELECTED"
    DEAL_CONFIRMING = "DEAL_CONFIRMING"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    CLOSED_WON = "CLOSED_WON"
    CLOSED_LOST = "CLOSED_LOST"
    ESCALATED = "ESCALATED"


TERMINAL = {TS.UNREACHABLE, TS.OPTED_OUT, TS.CLOSED_WON, TS.CLOSED_LOST}
PRE_ENGAGED = {TS.OUTREACH_SENT, TS.FOLLOW_UP_1, TS.PHONE_NUDGE, TS.NO_RESPONSE}
QUOTING = {TS.QUOTED, TS.NEGOTIATING, TS.FINAL_OFFER}

_T = {
    TS.DISCOVERED: {TS.CONTACT_RESOLVED, TS.UNREACHABLE},
    TS.CONTACT_RESOLVED: {TS.OUTREACH_SENT},
    TS.OUTREACH_SENT: {TS.FOLLOW_UP_1, TS.ENGAGED, TS.NO_RESPONSE},
    TS.FOLLOW_UP_1: {TS.PHONE_NUDGE, TS.ENGAGED, TS.NO_RESPONSE},
    TS.PHONE_NUDGE: {TS.ENGAGED, TS.NO_RESPONSE},
    TS.NO_RESPONSE: {TS.ENGAGED},
    TS.ENGAGED: {TS.PUSH_FOR_WRITTEN_OTD, TS.SUBSTITUTE_PROPOSED, TS.QUOTE_RECEIVED, TS.ENGAGED},
    TS.PUSH_FOR_WRITTEN_OTD: {TS.PUSH_FOR_WRITTEN_OTD, TS.IN_PERSON_ONLY, TS.QUOTE_RECEIVED, TS.ENGAGED},
    TS.IN_PERSON_ONLY: {TS.QUOTE_RECEIVED},
    TS.SUBSTITUTE_PROPOSED: {TS.QUOTE_RECEIVED, TS.ENGAGED},
    TS.QUOTE_RECEIVED: {TS.VALIDATING},
    TS.VALIDATING: {TS.REQUEST_ITEMIZATION, TS.QUOTED, TS.NEGOTIATING, TS.FINAL_OFFER},
    TS.REQUEST_ITEMIZATION: {TS.QUOTE_RECEIVED, TS.SUBSTITUTE_PROPOSED, TS.PUSH_FOR_WRITTEN_OTD, TS.ENGAGED},
    TS.QUOTED: {TS.NEGOTIATING, TS.QUOTE_RECEIVED, TS.SUBSTITUTE_PROPOSED, TS.FINAL_OFFER, TS.SHORTLISTED, TS.ELIMINATED},
    TS.NEGOTIATING: {TS.QUOTE_RECEIVED, TS.SUBSTITUTE_PROPOSED, TS.FINAL_OFFER, TS.NEGOTIATING, TS.SHORTLISTED, TS.ELIMINATED},
    TS.FINAL_OFFER: {TS.SHORTLISTED, TS.ELIMINATED, TS.QUOTE_RECEIVED, TS.SUBSTITUTE_PROPOSED},
    TS.SHORTLISTED: {TS.SELECTED, TS.ELIMINATED},
    TS.ELIMINATED: {TS.SELECTED},
    TS.SELECTED: {TS.DEAL_CONFIRMING, TS.ELIMINATED},
    TS.DEAL_CONFIRMING: {TS.DEAL_CONFIRMING, TS.APPOINTMENT_CONFIRMED},
    TS.APPOINTMENT_CONFIRMED: {TS.CLOSED_WON},
}
ANY_NON_TERMINAL = {TS.ESCALATED, TS.CLOSED_LOST, TS.OPTED_OUT}


class IllegalTransition(RuntimeError):
    pass


def allowed(src: TS, dst: TS) -> bool:
    if src in TERMINAL:
        return False
    if dst in ANY_NON_TERMINAL:
        return True
    return dst in _T.get(src, set())


class CampaignState(StrEnum):
    INTAKE = "INTAKE"
    PRICE_MODEL = "PRICE_MODEL"
    DISCOVERY = "DISCOVERY"
    HITL_1 = "HITL_1"
    OUTREACH = "OUTREACH"
    QUOTE_COLLECTION = "QUOTE_COLLECTION"
    NEGOTIATION_ROUNDS = "NEGOTIATION_ROUNDS"
    BEST_AND_FINAL = "BEST_AND_FINAL"
    PRESENT_SHORTLIST = "PRESENT_SHORTLIST"
    HITL_2 = "HITL_2"
    CONFIRM_DEAL = "CONFIRM_DEAL"
    HITL_3 = "HITL_3"
    SCHEDULE = "SCHEDULE"
    HITL_4 = "HITL_4"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    DONE = "DONE"
    FAILED = "FAILED"
